### ISSUE TITLE
Collapsibles

### ISSUE THREAD

**Issue by trevorsaint** [hmcts/frontend#13]
Add a collapsible component to allow users to gradually reveal information, whilst keeping the overall page uncluttered with information.

A typical example as shown below:

![image](https://user-images.githubusercontent.com/4989027/42935304-39fc7124-8b41-11e8-9d44-9c036b262be8.png)

@adamsilver to write scalable efficient Javascript.
@trevorsaint to style a responsive (progressively enhanced version)

**Comment by adamsilver** [comment]
Already exists?

**Comment by trevorsaint** [comment]
This exists. I will need to refactor the CSS. You will need to improve my JS :).

**Comment by adamsilver** [comment]
Best idea is we swap roles ;)

**Comment by adamsilver** [comment]
Doesn't this already exist in GOV.UK Frontend?

**Comment by adamsilver** [comment]
Moved to the design system backlog for discussion.
