### ISSUE TITLE
Primary nav component

### ISSUE THREAD

**Issue by adamsilver** [hmcts/frontend#28]
1. Add `hmcts-primary-navigation__container` element
2. Mixin the `hmcts-width-container` styles onto it
3. Set default `$hmcts-page-width` to 960 (a sensible default)
4. The mixin width should be a parameter that is set to the sensible default `$hmcts-page-width`
5. Set the default font size to 19px (and adjust spacing/padding/etc accordingly)

**Comment by adamsilver** [comment]
Same principle for sub nav

**Comment by trevorsaint** [comment]
This has been done for Primary nav component.

**Comment by adamsilver** [comment]
Make primary nav bold and more prominent.
