### ISSUE TITLE
Alert component spec

### ISSUE THREAD

**Issue by adamsilver** [hmcts/frontend#34]
```
<div class="hmcts-alert {% if params.classes %}{{ params.classes }}{% endif %}" role="status" aria-live="polite">
  {%- if params.icon %}<span class="hmcts-alert__icon {% if params.icon.classes %}{{ params.icon.classes }}{% endif %}">{{ params.icon.text }}</span>{% endif %}
  <span class="hmcts-alert__text">{{ params.html | safe if params.html else params.text }}</span>
</div>
```

Would be useful to consider different states for this. Error, success etc.

**Comment by adamsilver** [comment]
See this comprehensive rundown of alert patterns:
https://github.com/alphagov/govuk-design-system-backlog/issues/2

**Comment by trevorsaint** [comment]
@adamsilver these are the ones we did for JUI. I've tweaked them ever so slightly but these could be a start don’t you think?

Alert / Success
![success](https://user-images.githubusercontent.com/4989027/44188476-aa660d00-a115-11e8-9f91-4f5b2f4748a6.png)

Alert / Warning
![warning](https://user-images.githubusercontent.com/4989027/44188480-b05bee00-a115-11e8-8495-3a4ef1e8efcb.png)

**Comment by trevorsaint** [comment]
These have been added to an alert branch.
<img width="696" alt="image" src="https://user-images.githubusercontent.com/4989027/44190860-83610880-a120-11e8-9d7d-f205f15a4586.png">
@adamsilver we need to discuss in more detail.

**Comment by adamsilver** [comment]
Nice—what issues need discussing?

**Comment by trevorsaint** [comment]
@adamsilver more to review the approach if anything.

**Comment by trevorsaint** [comment]
Here is an informative alert i've quickly mocked up. May well add this into the design system as a third option.

Alert / Information
![information](https://user-images.githubusercontent.com/4989027/44263909-9ce57b80-a218-11e8-823d-d4d3e17b4729.png)

**Comment by adamsilver** [comment]
Cool

**Comment by trevorsaint** [comment]
In use:

![image](https://user-images.githubusercontent.com/4989027/44263994-e209ad80-a218-11e8-88a5-bf243b4aada1.png)
