### ISSUE TITLE
Please can up this SCSS to be specific to  [aria-current="page"]

### ISSUE THREAD

**Issue by frontr-uk** [hmcts/frontend#51]
https://github.com/hmcts/frontend/blob/a36c2efedf8930f4ba108c7dd429033289cc003a/src/components/sub-navigation/_sub-navigation.scss#L68

Before:
`.hmcts-sub-navigation__link[aria-current] {}`
After:
`.hmcts-sub-navigation__link[aria-current="page"] {}`

This will allow to always have aria-current in our code an only when the page is active it would assign the "page" value

**Comment by adamsilver** [comment]
We'd advise only putting aria-current in when you need it. But I can still update the SASS to accomodate this for you. I'll do that now.

**Comment by adamsilver** [comment]
Done—will be fixed in the next release.
