### ISSUE TITLE
Can't pass classes to menus inside identity bar

### ISSUE THREAD

**Issue by edwardhorsford** [hmcts/frontend#68]
### What would you like to change?
I wanted to pass classes to each of the menus I was using in the identity bar - so that I could hook them in js. After some searching, I realised classes isn't passed to the child macro.

FWIW, it would be good if the examples of menus used explicit classes for the js hooks - it wasn't obvious adding a class was even possible.

**Comment by adamsilver** [comment]
Will be fixed in the next release.
